CREATE OR REPLACE TRIGGER TRIGGER_INSERT_MOEDA
BEFORE INSERT ON DIV_MOEDA
FOR EACH ROW
BEGIN
	IF :NEW.SEQ_MOEDA IS NULL THEN
		SELECT (SEQ_COUNT+1) INTO :NEW.SEQ_MOEDA FROM SEQUENCE WHERE seq_name = 'seq_moeda';
		UPDATE SEQUENCE SET SEQ_COUNT = :NEW.SEQ_MOEDA WHERE seq_name = 'seq_moeda';
	END IF;
END;

CREATE OR REPLACE TRIGGER TRIGGER_INSERT_CREDOR
BEFORE INSERT ON DIV_CREDOR
FOR EACH ROW
BEGIN
	IF :NEW.SEQ_CREDOR IS NULL THEN
		SELECT (SEQ_COUNT+1) INTO :NEW.SEQ_CREDOR FROM SEQUENCE WHERE seq_name = 'seq_credor';
		UPDATE SEQUENCE SET SEQ_COUNT = :NEW.SEQ_CREDOR WHERE seq_name = 'seq_credor';
	END IF;
END;

CREATE OR REPLACE TRIGGER TRIGGER_INSERT_FINALIDADE
BEFORE INSERT ON DIV_FINALIDADE_OPERACAO
FOR EACH ROW
BEGIN
	IF :NEW.SEQ_FINALIDADE_OPERACAO IS NULL THEN
		SELECT (SEQ_COUNT+1) INTO :NEW.SEQ_FINALIDADE_OPERACAO FROM SEQUENCE WHERE seq_name = 'seq_finalidade_operacao';
		UPDATE SEQUENCE SET SEQ_COUNT = :NEW.SEQ_FINALIDADE_OPERACAO WHERE seq_name = 'seq_finalidade_operacao';
	END IF;
END;

CREATE OR REPLACE TRIGGER TRIGGER_INSERT_INDEXADOR
BEFORE INSERT ON DIV_INDEXADOR
FOR EACH ROW
BEGIN
	IF :NEW.SEQ_INDEXADOR IS NULL THEN
		SELECT (SEQ_COUNT+1) INTO :NEW.SEQ_INDEXADOR FROM SEQUENCE WHERE seq_name = 'seq_indexador';
		UPDATE SEQUENCE SET SEQ_COUNT = :NEW.SEQ_INDEXADOR WHERE seq_name = 'seq_indexador';
	END IF;
END;

CREATE OR REPLACE TRIGGER TRIGGER_INSERT_INST_FIN
BEFORE INSERT ON DIV_INSTITUICAO_FINANCEIRA
FOR EACH ROW
BEGIN
	IF :NEW.SEQ_INST_FINANCEIRA IS NULL THEN
		SELECT (SEQ_COUNT+1) INTO :NEW.SEQ_INST_FINANCEIRA FROM SEQUENCE WHERE seq_name = 'seq_inst_financeira';
		UPDATE SEQUENCE SET SEQ_COUNT = :NEW.SEQ_INST_FINANCEIRA WHERE seq_name = 'seq_inst_financeira';
	END IF;
END;