REM INSERTING into DIVIDA_PI_2021.DIV_TIP_DIVIDA
SET DEFINE OFF;
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('1','1',null,'Interna');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('2','1',null,'Externa');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('3','1',null,'Outro');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('4','1',null,'Empréstimo ou Financiamento');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('5','1',null,'Mobiliária');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('6','1',null,'Parcelamento previdenciário');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('7','1',null,'Parcelamento trabalhista');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('8','1',null,'Parcelamento tributário');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('9','1',null,'Precatórios');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('10','1',null,'Refinanciamento com a União');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('11','1',null,'Outras dívidas contratuais');
Insert into DIVIDA_PI_2021.DIV_TIP_DIVIDA (SEQ_TIPO_DIVIDA,FLG_ATIVO,DSC_TIP_DIVIDA,NOM_TIPO_DIVIDA) values ('12','1',null,'Outras dívidas não contratuais');
