Insert into DIVIDA_PI_2022.DIV_INDEXADOR (SEQ_INDEXADOR,ACRO_INDEXADOR,FLG_ATIVO,DSC_INDEXADOR,NOM_INDEXADOR,TIPO_MEDICAO,SEQ_FONTE_INFORMACAO) values ('1','TR','1',null,'TR','INDICE_MES',null);
Insert into DIVIDA_PI_2022.DIV_INDEXADOR (SEQ_INDEXADOR,ACRO_INDEXADOR,FLG_ATIVO,DSC_INDEXADOR,NOM_INDEXADOR,TIPO_MEDICAO,SEQ_FONTE_INFORMACAO) values ('4','TJLP','1',null,'TJLP','INDICE_MES',null);
Insert into DIVIDA_PI_2022.DIV_INDEXADOR (SEQ_INDEXADOR,ACRO_INDEXADOR,FLG_ATIVO,DSC_INDEXADOR,NOM_INDEXADOR,TIPO_MEDICAO,SEQ_FONTE_INFORMACAO) values ('2','SELIC','1',null,'SELIC','INDICE_MES',null);
Insert into DIVIDA_PI_2022.DIV_INDEXADOR (SEQ_INDEXADOR,ACRO_INDEXADOR,FLG_ATIVO,DSC_INDEXADOR,NOM_INDEXADOR,TIPO_MEDICAO,SEQ_FONTE_INFORMACAO) values ('3','CDI','1',null,'CDI','INDICE_MES',null);
