REM INSERTING into DIVIDA_PI_2021.DIV_TIP_CREDOR
SET DEFINE OFF;
Insert into DIVIDA_PI_2021.DIV_TIP_CREDOR (SEQ_TIPO_CREDOR,FLG_ATIVO,DESC_TIPO_CREDOR,NOM_TIPO_CREDOR) values ('2','1',null,'Empresa');
Insert into DIVIDA_PI_2021.DIV_TIP_CREDOR (SEQ_TIPO_CREDOR,FLG_ATIVO,DESC_TIPO_CREDOR,NOM_TIPO_CREDOR) values ('3','1',null,'Instituição Financeira Nacional');
Insert into DIVIDA_PI_2021.DIV_TIP_CREDOR (SEQ_TIPO_CREDOR,FLG_ATIVO,DESC_TIPO_CREDOR,NOM_TIPO_CREDOR) values ('4','1',null,'Instituição Financeira Internacional');
Insert into DIVIDA_PI_2021.DIV_TIP_CREDOR (SEQ_TIPO_CREDOR,FLG_ATIVO,DESC_TIPO_CREDOR,NOM_TIPO_CREDOR) values ('5','1',null,'Pessoa Física ');
Insert into DIVIDA_PI_2021.DIV_TIP_CREDOR (SEQ_TIPO_CREDOR,FLG_ATIVO,DESC_TIPO_CREDOR,NOM_TIPO_CREDOR) values ('6','1',null,'Outros');
Insert into DIVIDA_PI_2021.DIV_TIP_CREDOR (SEQ_TIPO_CREDOR,FLG_ATIVO,DESC_TIPO_CREDOR,NOM_TIPO_CREDOR) values ('1','1',null,'Empresa Estatal');
