REM INSERTING into DIVIDA_PI_2021.DIV_TIP_OPERACAO
SET DEFINE OFF;
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('2','1',null,'Concessão de garantia');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('3','1',null,'Emissão de Debêntures');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('4','1',null,'Emissão de Títulos Públicos');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('5','1',null,'Operação Contratual Externa');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('6','1',null,'Operação Contratual Externa (com garantia da união)');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('7','1',null,'Operação Contratual Interna');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('8','1',null,'Operação Contratual Interna (com garantia da União)');
Insert into DIVIDA_PI_2021.DIV_TIP_OPERACAO (SEQ_TIP_OPERACAO,FLG_ATIVO,DSC_TIP_OPERACAO,NOM_TIP_OPERACAO) values ('1','1',null,'Financiamento');
