REM INSERTING into DIVIDA_PI_2021.DIV_TIP_MUTUARIO
SET DEFINE OFF;
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('1','1',null,'Empresa Estatal');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('2','1',null,'Empresa não Estatal');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('3','1',null,'Instituição Financeira Nacional');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('4','1',null,'Instituição Financeira Internacional');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('5','1',null,'Município');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('6','1',null,'Outro-Pessoa Física');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('7','1',null,'Outro - Pessoa Jurídica de Direito Privado');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('8','1',null,'Outro - Pessoa Jurídica de Direito Público');
Insert into DIVIDA_PI_2021.DIV_TIP_MUTUARIO (SEQ_TIPO_MUTUARIO,FLG_ATIVO,DESC_TIPO_MUTUARIO,NOM_TIPO_MUTUARIO) values ('9','1',null,'Outros - não especificados');
