delete from divida_pi_2021.div_evento_tranche;
delete from divida_pi_2021.div_liberacao;
delete from divida_pi_2021.div_obrigacao;
delete from divida_pi_2021.div_tranche_contrato;
delete from divida_pi_2021.div_contrato;
delete from divida_pi_2021.div_moeda;
delete from divida_pi_2021.div_credor;
delete from divida_pi_2021.div_finalidade_operacao;
delete from divida_pi_2021.div_indexador;
delete from divida_pi_2021.div_instituicao_financeira;
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_evento_contrato';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_obrigacao';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_liberacao';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_tranche_contrato';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_contrato';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_moeda';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_credor';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_finalidade_operacao';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_indexador';
update divida_pi_2021.sequence set seq_count = 0  where seq_name = 'seq_inst_financeira';
alter trigger TRIGGER_INSERT_EVENTO_TRANCHE enable;
alter trigger TRIGGER_INSERT_OBRIGACAO enable;
alter trigger TRIGGER_INSERT_LIBERACAO enable;
alter trigger TRIGGER_INSERT_TRANCHE_CONT enable;
alter trigger TRIGGER_INSERT_CONTRATO enable;
alter trigger TRIGGER_INSERT_CREDOR enable;
alter trigger TRIGGER_INSERT_MOEDA enable;
alter trigger TRIGGER_INSERT_FINALIDADE enable;
alter trigger TRIGGER_INSERT_INDEXADOR enable;
alter trigger TRIGGER_INSERT_INST_FIN enable;

